apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wge-sa
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./leaf-clusters/wge-sa
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      templateNamespace: wge
