apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capi
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: wge
  path: ./cluster/bases/capi
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capi-templates
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: wge
    - name: capi
  path: ./clusters/management/capi
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capi-clusters
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: capi-templates
  path: ./clusters/management/clusters/default
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
